### ISSUE TITLE
🐞 - `cursor: pointer` is not set on color square though it's mentioned in code for `TuiInputColor`

### ISSUE THREAD

**Issue by viktorzdanovich** [Tinkoff/tui-editor#38]
### Playground Link

https://tinkoff.github.io/tui-editor/color-picker

### Description

For color square used inside `tui-input-color` cursor is set to `text` though according to the code it should be `pointer`
![Kapture 2023-07-17 at 11 51 24](https://github.com/Tinkoff/tui-editor/assets/19538300/f1cb7a07-00ce-476e-9945-0a059f4cf268)

### Angular version

> 12

### Taiga UI version

3.35.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [X] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by splincode** [comment]
@waterplea how and when did we plan to change this behavior?
https://github.com/Tinkoff/taiga-ui/blob/main/projects/core/styles/mixins/textfield.less#L299
